sudo: required
services:
- docker
language: cpp


# It is currently not possible to build manylinux packages for linux arm. Reasons are:
#   - The binary dependencies of pylon are newer than specified in manylinux2014
#   - There is no manylinux armhf docker container available
# - P=manylinux2014_armv7l A=cp35m
# - P=manylinux2014_armv7l A=cp36m
# - P=manylinux2014_armv7l A=cp37m
# - P=manylinux2014_armv7l A=cp38
# - P=manylinux2014_aarch64 A=cp35m
# - P=manylinux2014_aarch64 A=cp36m
# - P=manylinux2014_aarch64 A=cp37m
# - P=manylinux2014_aarch64 A=cp38


jobs:
  include:
    # manylinux2014_x86_64
    - arch: amd64
      env: P=manylinux2014_x86_64 A=cp35m
    - arch: amd64
      env: P=manylinux2014_x86_64 A=cp36m
    - arch: amd64
      env: P=manylinux2014_x86_64 A=cp37m
    - arch: amd64
      env: P=manylinux2014_x86_64 A=cp38
    # manylinux2014_i686
    - arch: amd64
      env: P=manylinux2014_i686 A=cp35m
    - arch: amd64
      env: P=manylinux2014_i686 A=cp36m
    - arch: amd64
      env: P=manylinux2014_i686 A=cp37m
    - arch: amd64
      env: P=manylinux2014_i686 A=cp38
    # linux_x86_64
    - arch: amd64
      env: P=linux_x86_64 A=cp34m
    - arch: amd64
      env: P=linux_x86_64 A=cp35m
    - arch: amd64
      env: P=linux_x86_64 A=cp36m
    - arch: amd64
      env: P=linux_x86_64 A=cp37m
    - arch: amd64
      env: P=linux_x86_64 A=cp38
    # linux_i686
    - arch: amd64
      env: P=linux_i686 A=cp34m
    - arch: amd64
      env: P=linux_i686 A=cp35m
    - arch: amd64
      env: P=linux_i686 A=cp36m
    - arch: amd64
      env: P=linux_i686 A=cp37m
    - arch: amd64
      env: P=linux_i686 A=cp38
    # linux_armv7l
    # armv7l is still build using qemu on x86, because it was not easily possible to build for armv7l (The best was armv8l using linux32 wrapper)
    # The tests are disabled for armv7l because installing the required numpy took too long and we hit the maximum allowed travis build time.
    - arch: amd64
      env: P=linux_armv7l A=cp34m ARGS="--disable-tests"
    - arch: amd64
      env: P=linux_armv7l A=cp35m ARGS="--disable-tests"
    - arch: amd64
      env: P=linux_armv7l A=cp36m ARGS="--disable-tests"
    - arch: amd64
      env: P=linux_armv7l A=cp37m ARGS="--disable-tests"
    - arch: amd64
      env: P=linux_armv7l A=cp38 ARGS="--disable-tests"
    # linux_aarch64
    - arch: arm64
      env: P=linux_aarch64 A=cp34m
    - arch: arm64
      env: P=linux_aarch64 A=cp35m
    - arch: arm64
      env: P=linux_aarch64 A=cp36m
    - arch: arm64
      env: P=linux_aarch64 A=cp37m
    - arch: arm64
      env: P=linux_aarch64 A=cp38
  allow_failures:
    # manylinux fails, because the runtime dependencies of current pylon are higher than manylinux2014.
    # The jobs are still kept in here to keep the mechanics alive.
    # manylinux2014_x86_64
    - arch: amd64
      env: P=manylinux2014_x86_64 A=cp35m
    - arch: amd64
      env: P=manylinux2014_x86_64 A=cp36m
    - arch: amd64
      env: P=manylinux2014_x86_64 A=cp37m
    - arch: amd64
      env: P=manylinux2014_x86_64 A=cp38
    # manylinux2014_i686
    - arch: amd64
      env: P=manylinux2014_i686 A=cp35m
    - arch: amd64
      env: P=manylinux2014_i686 A=cp36m
    - arch: amd64
      env: P=manylinux2014_i686 A=cp37m
    - arch: amd64
      env: P=manylinux2014_i686 A=cp38


install:
- cd $TRAVIS_BUILD_DIR
- mkdir pylon_installer && cd pylon_installer
- |
  for PYLON_VERSION in 6.1.0.19674_x86 6.1.1.19861_x86_64 6.1.3.20159_armhf 6.1.3.20159_aarch64 ; do
      travis_retry curl -sSfL -O "${PYLON_DOWNLOAD_URL_BASE}pylon_${PYLON_VERSION}_setup.tar.gz"
  done

- echo "Pylon Installer:" && ls

script:
- cd $TRAVIS_BUILD_DIR
- |
  if [ "$TRAVIS_CPU_ARCH" == "amd64" ]; then
      docker run --rm --privileged multiarch/qemu-user-static:register --reset
  fi
- "./scripts/build/build-arch.sh --platform-tag $P --abi-tag $A --pylon-dir ./pylon_installer $ARGS"

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: R46oPGgeRYe2GB5JLMW8doUQf4lQx1oa+Jvr7HMbZpoVHC/EV37l9wrYLkY3BHLc3DUB6Xnc94Dc0IxEnQ3AV+vuSmDTDqdsEo7KYF+ZRMab+J4XpzLvP7E0QHwslXhCIUraEtTom4UydV5Oh6Zz4KA5utNjE9O7KUHHatcccq7/fP/8M2aZocVkkwOzNfl91tTT1nJXMtf10XGKkdI1O0VwSLkXjihIbPDANx53RWCgJgD3JGwbsDQf3lg6mzaJyx7DJ0BVSZT5tErE32pkLJqXNLsy/RQ1lPu0Ycf1HxrgYqH8NvDu4KxfKw41dcMkp6gN4ELhuVOChkztvxB1QPKHn6SdJL86+ipOZiycdnqvAAg1UD2q9idCDE4KhrD8PBJXme/1qLq578NA2PmXbWEGuHk69N/CNWhg898pFUQb600LhpsT28J7HVxGOrELr/6W0RNuEA0YCemfhDm5CQlFw8GVQ4DdFOM6dMyeeQnuWbXKQow9W0ZH/Hf8cklLfvYRYZxoulHzOF6Ley1MMVO2RHWnkZ078Xatm37El2oHkv1xxr/7Yo8GZyKTzaRKrsemtIFnuCxmK/JKGhKJlgtn6en4PL99X4EjmokjL5dhXSgz6jGb72xK7V+Xo5N6DH5t4p5huHXO8HXd5Sq3jHXD5eOZu5iHiwdrkzcJgkc=
  file_glob: true
  file: dist/*
  on:
    repo: basler/pypylon
    branch: master
    tags: true
