# Copyright (c) 2023-2026 Etaluma, Inc. MIT License. See LICENSE file.

"""Structural typing protocols for motor and LED drivers.

These Protocol classes define the public interface that all motor and LED
driver implementations must satisfy.  They are used for static type checking
only — there is zero runtime overhead.

Usage:
    from drivers.protocols import MotorBoardProtocol, LEDBoardProtocol

    def do_something(motor: MotorBoardProtocol) -> None:
        motor.move_abs_pos('Z', 5000)

All implementations (MotorBoard, SimulatedMotorBoard, NullMotionBoard,
LEDBoard, SimulatedLEDBoard, NullLEDBoard) satisfy these protocols by
duck typing — no inheritance required.
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class MotorBoardProtocol(Protocol):
    """Protocol defining the motor driver interface.

    All motor driver implementations (MotorBoard, SimulatedMotorBoard,
    NullMotionBoard) must satisfy this interface.
    """

    # --- Connection ---
    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def is_connected(self) -> bool: ...

    # --- Movement ---
    def move(self, axis: str, steps: int) -> None: ...
    def move_abs_pos(self, axis: str, pos: float,
                     overshoot_enabled: bool = True,
                     ignore_limits: bool = False) -> None: ...
    def move_rel_pos(self, axis: str, um: float,
                     overshoot_enabled: bool = False) -> None: ...

    # --- Position queries ---
    def target_pos(self, axis: str) -> float | None: ...
    def current_pos(self, axis: str) -> float | None: ...
    def target_pos_steps(self, axis: str) -> int | None: ...
    def current_pos_steps(self, axis: str) -> int | None: ...

    # --- Status ---
    def target_status(self, axis: str) -> bool: ...
    def home_status(self, axis: str) -> bool | str: ...
    def reference_status(self, axis: str) -> str | int: ...
    def limit_switch_status(self, axis: str) -> tuple[int, int]: ...

    # --- Homing ---
    def zhome(self) -> bool: ...
    def home(self) -> bool: ...
    def thome(self) -> bool: ...
    def has_turret(self) -> bool: ...
    def has_homed(self) -> bool: ...
    def has_thomed(self) -> bool: ...

    # --- Info ---
    def fullinfo(self) -> dict: ...
    def get_microscope_model(self) -> str | None: ...
    def get_axes_config(self) -> dict: ...
    def get_axis_limits(self, axis: str) -> dict | None: ...
    def get_current_firmware(self) -> str | None: ...

    # --- Acceleration ---
    def acceleration_limit(self, axis: str, parameter: str) -> int: ...
    def acceleration_limits(self) -> dict: ...
    def set_acceleration_limit(self, axis: str, parameter: str,
                               val_pct: int) -> None: ...
    def set_acceleration_limits(self, val_pct: int) -> None: ...

    # --- Precision mode ---
    def set_precision_mode(self, axis: str, enabled: bool) -> None: ...

    # --- SPI ---
    def spi_read(self, axis: str, addr: int) -> str: ...
    def spi_write(self, axis: str, addr: int,
                  payload: int | str) -> str: ...

    # --- Coordinate transforms ---
    def z_ustep2um(self, ustep: int) -> float: ...
    def z_um2ustep(self, um: float) -> int: ...
    def xy_ustep2um(self, ustep: int) -> float: ...
    def xy_um2ustep(self, um: float) -> int: ...
    def t_ustep2deg(self, ustep: int) -> float: ...
    def t_ustep2pos(self, ustep: int) -> int: ...
    def t_deg2ustep(self, degrees: float) -> int: ...
    def t_pos2ustep(self, position: int) -> int: ...

    # --- Serial ---
    def exchange_command(self, command: str,
                         response_numlines: int = 1,
                         timeout: float | None = None) -> str | None: ...


@runtime_checkable
class LEDBoardProtocol(Protocol):
    """Protocol defining the LED driver interface.

    All LED driver implementations (LEDBoard, SimulatedLEDBoard,
    NullLEDBoard) must satisfy this interface.
    """

    # --- Connection ---
    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def is_connected(self) -> bool: ...

    # --- Core LED control ---
    def led_on(self, channel: int, mA: int,
               block: bool = False, timeout: float = 5.0) -> None: ...
    def led_off(self, channel: int) -> None: ...
    def led_on_fast(self, channel: int, mA: int) -> None: ...
    def led_off_fast(self, channel: int) -> None: ...
    def leds_off(self) -> None: ...
    def leds_off_fast(self) -> None: ...
    def leds_enable(self) -> None: ...
    def leds_disable(self) -> None: ...

    # --- State queries ---
    def get_led_ma(self, color: str) -> int: ...
    def is_led_on(self, color: str) -> bool: ...
    def get_led_state(self, color: str) -> dict: ...
    def get_led_states(self) -> dict: ...

    # --- Channel mapping ---
    def color2ch(self, color: str) -> int: ...
    def ch2color(self, channel: int) -> str: ...

    # --- Diagnostics ---
    def read_led_current(self, channel: int) -> float | None: ...

    # --- Serial ---
    def exchange_command(self, command: str, **kwargs) -> str | None: ...
